<?xml version="1.0"?>
<package format="3">
  <name>circ_chassis_teleop</name>
  <version>0.1.0</version>
  <description>Joystick teleoperation for CIRC rover chassis using joy + teleop_twist_joy.</description>
  <maintainer email="todo@todo.todo">TODO</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <exec_depend>joy</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>teleop_twist_keyboard</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
